# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Install Dependencies
        run: yarn
        
      - name: Build
        run: yarn build
        
      # Then we must send all this config to our EC2 instance via SCP.
      # github.com/marketplace/actions/scp-files
      
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "., !node_modules, !ormconfig.json, !docker-compose.yml"
          target: "~/app/rentx-api"
          
      - name: Update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/rentx-api
            yarn
            ./node_modules/.bin/typeorm migration:run
            pm2 restart rentx_api
